kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-deployment
  labels:
    app: acrsetup
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: container
          image: 'myacrsetup.azurecr.io/simple-flask-app:latest'
          ports:
            - containerPort: 5000
              protocol: TCP
      imagePullSecrets:
        - name: acr-secret
