kind: Secret
apiVersion: v1
metadata:
  name: acr-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJteWFjcnNldHVwLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJteWFjcnNldHVwIiwicGFzc3dvcmQiOiJtd2FQQzhvMWZzVzB2bGZpU05aZ3UxczRYTWpLTXozQTh2YTViMUpNZ3orQUNSQ3hGQWRUIiwiYXV0aCI6ImJYbGhZM0p6WlhSMWNEcHRkMkZRUXpodk1XWnpWekIyYkdacFUwNWFaM1V4Y3pSWVRXcExUWG96UVRoMllUVmlNVXBOWjNvclFVTlNRM2hHUVdSVSIsImVtYWlsIjoiIn19fQ==
