name: Build with Podman

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Podman install
        run: podman --version && ls -ltr

      - name: Build image with Podman
        run: |
          podman build -t simple-flask-app -f python-app/.

      - name: List images
        run: podman images

      - name: Tag images
        run: podman tag localhost/simple-flask-app:latest myacrsetup.azurecr.io/simple-flask-app:latest

      - name: ACR login
        run: podman login -u myacrsetup -p ${{ secrets.ACR_PASSWORD }} myacrsetup.azurecr.io

      - name: Push image to ACR
        run: podman push myacrsetup.azurecr.io/simple-flask-app:latest
